import { app, BrowserWindow, shell, ipcMain, dialog } from 'electron';
import path from 'path';
import fs from 'fs/promises';
import { exec } from 'child_process';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const isDev = process.argv.includes('--dev');
const DEV_PORT = 5173;

let mainWindow;

async function waitForDevServer(url, maxAttempts = 30) {
  for (let i = 0; i < maxAttempts; i++) {
    try {
      await fetch(url);
      return true;
    } catch {
      await new Promise((r) => setTimeout(r, 1000));
    }
  }
  return false;
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 900,
    minHeight: 600,
    title: 'Cognia SDLC Crew',
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  if (isDev) {
    mainWindow.loadURL(`http://localhost:${DEV_PORT}`);
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  } else {
    // Load from local files — API calls go to EC2 server
    const indexPath = path.join(__dirname, '..', 'dist', 'index.html');
    mainWindow.loadFile(indexPath);
  }

  // Open external links in default browser
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: 'deny' };
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// IPC: Native folder picker dialog
ipcMain.handle('select-folder', async () => {
  const result = await dialog.showOpenDialog(mainWindow, {
    properties: ['openDirectory'],
    title: 'Select Project Folder',
  });
  if (result.canceled || result.filePaths.length === 0) return null;
  return result.filePaths[0];
});

// IPC: Index codebase for project context
ipcMain.handle('index-codebase', async (event, repoPath) => {
  try {
    const { indexCodebase } = await import('../server/utils/codebaseIndexer.js');
    const context = await indexCodebase(repoPath);
    if (!context) return { ok: false, error: 'Could not index codebase' };
    return { ok: true, context, chars: context.length };
  } catch (err) {
    return { ok: false, error: err.message };
  }
});

// IPC: Write planning docs to local project directory
ipcMain.handle('write-plans', async (event, repoPath, files, featureName, targetBranch) => {
  try {
    const sdlcDir = path.join(repoPath, '.sdlc');
    await fs.mkdir(sdlcDir, { recursive: true });

    // Latest folder (always overwritten — what Claude Code reads)
    const latestDir = path.join(sdlcDir, 'latest');
    await fs.mkdir(latestDir, { recursive: true });

    // Timestamped folder (permanent archive)
    const dateStr = new Date().toISOString().slice(0, 10);
    const slug = (featureName || 'feature').toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
    const archiveDir = path.join(sdlcDir, `${dateStr}_${slug}`);
    await fs.mkdir(archiveDir, { recursive: true });

    const written = [];
    for (const file of files) {
      const latestPath = path.join(latestDir, file.name);
      const archivePath = path.join(archiveDir, file.name);
      await fs.writeFile(latestPath, file.content, 'utf-8');
      await fs.writeFile(archivePath, file.content, 'utf-8');
      written.push(latestPath);
    }

    const branch = targetBranch || 'develop';
    const branchSlug = slug || 'feature';

    // Write INSTRUCTIONS.md to .sdlc/latest/
    const instructions = `# Implementation Instructions

Generated by Cognia SDLC Crew on ${new Date().toISOString().slice(0, 16).replace('T', ' ')}

## Git Workflow

1. Checkout the target branch and pull latest:
   \`\`\`
   git checkout ${branch} && git pull origin ${branch}
   \`\`\`

2. Create a feature branch:
   \`\`\`
   git checkout -b feature/${branchSlug}
   \`\`\`

3. Read the planning documents in this folder:
   - \`architecture-design.md\` — Architecture and system design
   - \`implementation-plan.md\` — Detailed task breakdown and code specs
   - \`qa-report.md\` — Test plan and QA checklist

4. Implement following the implementation plan step by step

5. After implementation, verify against the QA checklist in \`qa-report.md\`

6. Run tests to ensure everything passes

7. Commit with meaningful messages:
   \`\`\`
   git add -A
   git commit -m "feat: ${featureName || 'implement feature'}"
   \`\`\`

8. Push and create a Pull Request targeting \`${branch}\`:
   \`\`\`
   git push -u origin feature/${branchSlug}
   gh pr create --base ${branch} --title "feat: ${featureName || 'implement feature'}" --body "Implementation based on SDLC planning docs in .sdlc/latest/"
   \`\`\`

## Rules
- Follow existing code patterns in this project
- Run tests after implementation
- Don't modify files outside the scope of this feature
- Create small, focused commits
- All new files should follow the project's naming conventions
`;
    await fs.writeFile(path.join(latestDir, 'INSTRUCTIONS.md'), instructions, 'utf-8');
    await fs.writeFile(path.join(archiveDir, 'INSTRUCTIONS.md'), instructions, 'utf-8');

    // Write .claude/commands/implement.md — Claude Code slash command
    const claudeDir = path.join(repoPath, '.claude', 'commands');
    await fs.mkdir(claudeDir, { recursive: true });

    const implementCmd = `Read the SDLC planning documents and implement the feature.

## Steps

1. First, read all planning documents:
   - \`.sdlc/latest/INSTRUCTIONS.md\` — Git workflow and rules
   - \`.sdlc/latest/architecture-design.md\` — Architecture design
   - \`.sdlc/latest/implementation-plan.md\` — Detailed implementation plan
   - \`.sdlc/latest/qa-report.md\` — QA checklist

2. Create a feature branch from \`${branch}\`:
   \`\`\`
   git checkout ${branch} && git pull origin ${branch}
   git checkout -b feature/<short-name-from-plan>
   \`\`\`

3. Follow the implementation plan step by step. For each task:
   - Read the existing files referenced in the plan
   - Make the changes described
   - Follow existing code patterns and conventions
   - Add proper error handling and validation

4. After all tasks are complete:
   - Run the test suite (npm test, or whatever the project uses)
   - Fix any failing tests
   - Verify against the QA checklist in qa-report.md

5. Commit and push:
   \`\`\`
   git add -A
   git commit -m "feat: <feature-name-from-plan>"
   git push -u origin feature/<short-name>
   \`\`\`

6. Create a Pull Request:
   \`\`\`
   gh pr create --base ${branch} --title "feat: <feature-name>" --body "## Summary\\n\\nImplementation based on SDLC planning docs.\\n\\n## Planning Docs\\n- Architecture: .sdlc/latest/architecture-design.md\\n- Implementation: .sdlc/latest/implementation-plan.md\\n- QA: .sdlc/latest/qa-report.md"
   \`\`\`

## Important Rules
- Follow the architecture document exactly
- Match existing code style and patterns
- Include all imports, exports, and dependencies
- Add tests for new functionality
- Don't leave TODO comments — implement everything completely
`;
    await fs.writeFile(path.join(claudeDir, 'implement.md'), implementCmd, 'utf-8');

    // Write .sdlc/README.md
    const readme = `# SDLC Planning Documents

Generated by Cognia SDLC Crew

- \`latest/\` — Most recent planning docs (overwritten each run)
- Timestamped folders — Permanent archive of each planning run

## Usage with Claude Code

Run the implement command:
\`\`\`
/implement
\`\`\`

Or manually:
\`\`\`
claude "Read .sdlc/latest/ and implement the plan"
\`\`\`
`;
    await fs.writeFile(path.join(sdlcDir, 'README.md'), readme, 'utf-8');

    return { ok: true, directory: latestDir, archiveDir, files: written };
  } catch (err) {
    return { ok: false, error: err.message };
  }
});

// IPC: Launch Claude Code (Desktop or Terminal)
ipcMain.handle('launch-claude-code', async (event, repoPath, mode) => {
  const prompt = `Read the planning docs in ${repoPath}/.sdlc/latest/ and implement the plan. Start with architecture-design.md, then follow implementation-plan.md step by step. Verify against qa-report.md.`;
  const platform = process.platform;

  // Copy prompt to clipboard
  try {
    const { clipboard } = await import('electron');
    clipboard.default?.writeText?.(prompt) || require('electron').clipboard.writeText(prompt);
  } catch {}

  if (mode === 'terminal') {
    return new Promise(async (resolve) => {
      if (platform === 'darwin') {
        try {
          // Write a temp shell script
          const sdlcDir = path.join(repoPath, '.sdlc');
          await fs.mkdir(sdlcDir, { recursive: true });
          const tmpScript = path.join(sdlcDir, '.launch-claude.command');
          await fs.writeFile(tmpScript, `#!/bin/bash\ncd "${repoPath}"\nclaude\n`, { mode: 0o755 });
          // .command files auto-open in Terminal on macOS
          shell.openPath(tmpScript).then((err) => {
            if (err) return resolve({ ok: true, method: 'manual', message: `Run: cd "${repoPath}" && claude` });
            resolve({ ok: true, method: 'terminal', message: 'Claude Code launched in Terminal! Type /implement to start.' });
          });
        } catch (e) {
          resolve({ ok: true, method: 'manual', message: `Run: cd "${repoPath}" && claude` });
        }
      } else if (platform === 'win32') {
        try {
          const batFile = path.join(repoPath, '.sdlc', 'launch-claude.bat');
          await fs.mkdir(path.join(repoPath, '.sdlc'), { recursive: true });
          await fs.writeFile(batFile, `@echo off\ncd /d "${repoPath}"\nclaude\n`);
          shell.openPath(batFile);
          resolve({ ok: true, method: 'terminal', message: 'Claude Code launched!' });
        } catch (e) {
          resolve({ ok: true, method: 'manual', message: `Run: cd "${repoPath}" && claude` });
        }
      } else {
        exec(`x-terminal-emulator -e bash -c 'cd "${repoPath}" && claude'`, (err) => {
          if (err) return resolve({ ok: true, method: 'manual', message: `Run: cd "${repoPath}" && claude` });
          resolve({ ok: true, method: 'terminal', message: 'Claude Code launched in Terminal!' });
        });
      }
    });
  }

  // Desktop mode
  return new Promise((resolve) => {
    const appNames = ['Claude', 'Claude Desktop', 'claude'];
    let tried = 0;
    const tryNext = () => {
      if (tried >= appNames.length) {
        return resolve({ ok: true, method: 'clipboard', message: 'Claude Desktop not found. Prompt copied to clipboard.' });
      }
      const name = appNames[tried++];
      const cmd = platform === 'darwin' ? `open -a "${name}"` : platform === 'win32' ? `start "" "${name}"` : `xdg-open "${name}"`;
      exec(cmd, (err) => {
        if (err) return tryNext();
        resolve({ ok: true, method: 'desktop', message: `Claude Desktop opened! Prompt copied to clipboard — press Cmd+V to paste.` });
      });
    };
    tryNext();
  });
});

app.whenReady().then(async () => {
  if (isDev) {
    console.log('Waiting for dev servers...');
    const ready = await waitForDevServer(`http://localhost:${DEV_PORT}`);
    if (!ready) {
      console.error('Dev server not available. Make sure Vite is running on port', DEV_PORT);
    }
  }

  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
